# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-14 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0011_auto_20200214_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
